### ISSUE TITLE
/usr/bin/ld: cannot find -lc++

### ISSUE THREAD

**Issue by lf94** [AriusX7/lzham#1]
Despite having g++ (and installing build-essential on debian), I'm unable to compile. Any ideas?

**Comment by AriusX7** [comment]
It's related to the build script used in the [`lzham-sys`] crate. The compiler expects to link `libc++` on all platforms but it's not available.

Unfortunately, I haven't been able to figure out the correct build script for systems other than macOS and Ubuntu.

[`lzham-sys`]: https://github.com/AriusX7/lzham-sys

**Comment by AriusX7** [comment]
Closing this since the issue is due to the [`lzham-sys`](https://github.com/AriusX7/lzham-sys) crate.
